apiVersion: v1
kind: Service
metadata:
  name: travel-api-service
  namespace: travel

spec:
  type: ClusterIP

  selector:
    app: travel-api

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080