spring:
  config:
    import: optional:file:.env.local[.properties]

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT:3307}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
external:
  kakao-mobility:
    base-url: https://apis-navi.kakaomobility.com
    rest-api-key: ${KAKAO_REST_API_KEY:}