spring:
  config:
    import: optional:file:.env.local[.properties]

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
external:
  kakao-mobility:
    base-url: https://apis-navi.kakaomobility.com
    rest-api-key: ${KAKAO_REST_API_KEY:}

  opinet:
    base-url: https://www.opinet.co.kr
    api-key: ${OPINET_API_KEY:}
